### ISSUE TITLE
API naming

### ISSUE THREAD

**Issue by petebacondarwin** [btford/007#3]
I found it a little difficult to grok what 007 did from its usage in metahub.  I wonder if it would be clearer if the library returned an object rather than a function.  This object could contain an object that would make it clear what its function was:

``` javascript
var OhOh7 = require('007');
var someObj = require('someLib');
var someSpiedOnObj = OhOh7.spyOn(someObj);
```

**Comment by btford** [comment]
:+1: excellent suggestion

**Comment by petebacondarwin** [comment]
Even better, it would be nice if it worked in-place on the object rather than returning a new object.  That way, I could simply do:

``` javascript
OhOh7.spyOn(someObj);
```
